### ISSUE TITLE
Deploy to Heroku - Internal Server Error

### ISSUE THREAD

**Issue by deejay-hub** [heroku/einstein-vision-node#7]
Standard 'Deploy to Heroku' all default options. Results in the following error when trying to upload a photo.

2018-11-16T05:32:42.563777+00:00 app[web.1]: TypeError: Cannot read property 'access_mode' of null
2018-11-16T05:32:42.563795+00:00 app[web.1]:     at build_upload_params (/app/node_modules/cloudinary/lib-es5/utils/index.js:320:25)
2018-11-16T05:32:42.563797+00:00 app[web.1]:     at /app/node_modules/cloudinary/lib-es5/uploader.js:69:18
2018-11-16T05:32:42.563799+00:00 app[web.1]:     at call_api (/app/node_modules/cloudinary/lib-es5/uploader.js:450:37)
2018-11-16T05:32:42.563800+00:00 app[web.1]:     at Object.upload (/app/node_modules/cloudinary/lib-es5/uploader.js:68:10)
2018-11-16T05:32:42.563802+00:00 app[web.1]:     at /app/lib/cloudinary-resize-image.js:20:27
2018-11-16T05:32:42.563803+00:00 app[web.1]:     at cloudinaryResizeImage (/app/lib/cloudinary-resize-image.js:18:10)
2018-11-16T05:32:42.563804+00:00 app[web.1]:     at /app/node_modules/episode-7/index.js:94:23

**Comment by trevorscott** [comment]
@deejay-hub we have [updated](https://github.com/heroku/einstein-vision-node/pull/9) this project and as a result fixed the issue that you were encountering.
